-- Create table for storing commercial approaches generated by AI
CREATE TABLE IF NOT EXISTS public.lead_abordagens_comerciais (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    lead_id UUID REFERENCES public.leads_salvos(id) ON DELETE CASCADE,
    cnae VARCHAR,
    porte_empresa VARCHAR,
    dores_principais JSONB DEFAULT '[]'::jsonb,
    abordagem_gerada TEXT,
    personas_decisoras JSONB DEFAULT '[]'::jsonb,
    argumentos_venda JSONB DEFAULT '[]'::jsonb,
    proximos_passos JSONB DEFAULT '[]'::jsonb,
    criado_em TIMESTAMP DEFAULT NOW(),
    atualizado_em TIMESTAMP DEFAULT NOW()
);

-- Add index on lead_id for performance
CREATE INDEX IF NOT EXISTS idx_lead_abordagens_comerciais_lead_id 
    ON public.lead_abordagens_comerciais USING btree (lead_id);

-- Create function and trigger to auto-update atualizado_em
CREATE OR REPLACE FUNCTION public.update_lead_abordagens_comerciais_updated_at()
RETURNS trigger AS $$
BEGIN
    NEW.atualizado_em = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS update_lead_abordagens_comerciais_updated_at_trigger ON public.lead_abordagens_comerciais;
CREATE TRIGGER update_lead_abordagens_comerciais_updated_at_trigger
    BEFORE UPDATE ON public.lead_abordagens_comerciais
    FOR EACH ROW EXECUTE FUNCTION public.update_lead_abordagens_comerciais_updated_at();

-- Enable RLS
ALTER TABLE public.lead_abordagens_comerciais ENABLE ROW LEVEL SECURITY;

-- Add RLS policy
DROP POLICY IF EXISTS "Enable ALL for authenticated users on lead_abordagens_comerciais" ON public.lead_abordagens_comerciais;
CREATE POLICY "Enable ALL for authenticated users on lead_abordagens_comerciais" 
    ON public.lead_abordagens_comerciais 
    FOR ALL 
    TO authenticated 
    USING (true) 
    WITH CHECK (true);
